angular.module('messageModule').constant('locationConsts', {
    GET: 'GET_LOCATION_DATA',
    SEND: 'SEND_LOCATION_DATA',
	GET_LOCATION_DETAILS: 'GET_LOCATION_DETAILS',
    RETRIEVED_LOCATION_DETAILS: 'RETRIEVED_LOCATION_DETAILS'
});
